version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/pg_log
    ports:
      - 5432:5432
  tests:
    build:
      context: .
      target: test
    container_name: testing
    working_dir: /app
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
     # - ./src:/app/src 
     # - ./migrations:/app/migrations
     # - ./tests:/app/tests
     # - ./.env:/app/.env
     # - ./Cargo.lock:/app/Cargo.lock
     # - ./Cargo.toml:/app/Cargo.toml

