version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/pg_log
    ports:
      - 5432:5432
  backend_tests:
    build: .
    container_name: backend_tests
    env_file: .env
    command: [ cargo, test ]
    depends_on:
      - db
  backend:
    build: .
    container_name: backend
    env_file: .env
    command: [ cargo, run ]
    ports:
      - 8080:8080
    depends_on:
      - db
