version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/pg_log
    ports:
      - 5432:5432
  tests:
    image: rust:latest
    container_name: testing
    working_dir: /app
    command: cargo test
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

