DROP SCHEMA IF EXISTS testing CASCADE;
CREATE SCHEMA testing;

CREATE TABLE testing.users (
	id  BIGSERIAL PRIMARY KEY,
	first_name  VARCHAR(200) NOT NULL,
	last_name   VARCHAR(200) NOT NULL
);

CREATE TABLE testing.articles (
	id  BIGSERIAL PRIMARY KEY,
	title       VARCHAR(200) NOT NULL,
	content     VARCHAR(200) NOT NULL,
	created_by  BIGINT NOT NULL REFERENCES testing.users (id)
);

GRANT ALL PRIVILEGES ON SCHEMA testing TO test_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA testing TO test_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA testing TO test_user;
